name: 'BrowserStack Test'
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install 

      - name: Install BrowserStack Cypress CLI
        run: npm install -g browserstack-cypress-cli

      - name: Run Cypress tests on BrowserStack
        run: browserstack-cypress run --sync